//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tracker.Resources.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Team Member.
        /// </summary>
        public static string Add_Team_Member_Title {
            get {
                return ResourceManager.GetString("Add_Team_Member_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string ai {
            get {
                return ResourceManager.GetString("ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string android {
            get {
                return ResourceManager.GetString("android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architect.
        /// </summary>
        public static string architect {
            get {
                return ResourceManager.GetString("architect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Science.
        /// </summary>
        public static string data_science {
            get {
                return ResourceManager.GetString("data_science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer.
        /// </summary>
        public static string engineer {
            get {
                return ResourceManager.GetString("engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full stack.
        /// </summary>
        public static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string ios {
            get {
                return ResourceManager.GetString("ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior level.
        /// </summary>
        public static string junior {
            get {
                return ResourceManager.GetString("junior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Birthday.
        /// </summary>
        public static string Label_Birthday {
            get {
                return ResourceManager.GetString("Label_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        public static string Label_BirthdayColon {
            get {
                return ResourceManager.GetString("Label_BirthdayColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Label_Cell {
            get {
                return ResourceManager.GetString("Label_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Facebook profile link.
        /// </summary>
        public static string Label_Facebook {
            get {
                return ResourceManager.GetString("Label_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hire Date.
        /// </summary>
        public static string Label_HireDate {
            get {
                return ResourceManager.GetString("Label_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date:.
        /// </summary>
        public static string Label_HireDateColon {
            get {
                return ResourceManager.GetString("Label_HireDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Instagram profile link.
        /// </summary>
        public static string Label_Instagram {
            get {
                return ResourceManager.GetString("Label_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Label_JobTitle {
            get {
                return ResourceManager.GetString("Label_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title:.
        /// </summary>
        public static string Label_JobTitleColon {
            get {
                return ResourceManager.GetString("Label_JobTitleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter LinkedIn Profile Url.
        /// </summary>
        public static string Label_LinkIn {
            get {
                return ResourceManager.GetString("Label_LinkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Label_NickName {
            get {
                return ResourceManager.GetString("Label_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string Label_Role {
            get {
                return ResourceManager.GetString("Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of expertise:.
        /// </summary>
        public static string Label_Speciality {
            get {
                return ResourceManager.GetString("Label_Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Termination Date.
        /// </summary>
        public static string Label_TermDate {
            get {
                return ResourceManager.GetString("Label_TermDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination Date:.
        /// </summary>
        public static string Label_TerminationDateColon {
            get {
                return ResourceManager.GetString("Label_TerminationDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter X prolfile link.
        /// </summary>
        public static string Label_XTwitter {
            get {
                return ResourceManager.GetString("Label_XTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacOS.
        /// </summary>
        public static string mac_os {
            get {
                return ResourceManager.GetString("mac_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Tracker.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string mgr {
            get {
                return ResourceManager.GetString("mgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid level.
        /// </summary>
        public static string mid {
            get {
                return ResourceManager.GetString("mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Engineer.
        /// </summary>
        public static string principal {
            get {
                return ResourceManager.GetString("principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance .
        /// </summary>
        public static string qa {
            get {
                return ResourceManager.GetString("qa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string RadioButton_Active {
            get {
                return ResourceManager.GetString("RadioButton_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Theme.
        /// </summary>
        public static string RadioButton_Black {
            get {
                return ResourceManager.GetString("RadioButton_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Theme.
        /// </summary>
        public static string RadioButton_Gold {
            get {
                return ResourceManager.GetString("RadioButton_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string RadioButton_Inactive {
            get {
                return ResourceManager.GetString("RadioButton_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string RadioButton_Light {
            get {
                return ResourceManager.GetString("RadioButton_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior level.
        /// </summary>
        public static string senior {
            get {
                return ResourceManager.GetString("senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new team member.
        /// </summary>
        public static string ToolTip_AddMember {
            get {
                return ResourceManager.GetString("ToolTip_AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ToolTip_Edit {
            get {
                return ResourceManager.GetString("ToolTip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to LinkedIn Profile.
        /// </summary>
        public static string ToolTip_LinkedIn {
            get {
                return ResourceManager.GetString("ToolTip_LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolTip_Save {
            get {
                return ResourceManager.GetString("ToolTip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolTip_Settings {
            get {
                return ResourceManager.GetString("ToolTip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web UI.
        /// </summary>
        public static string web_ui {
            get {
                return ResourceManager.GetString("web_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string windows {
            get {
                return ResourceManager.GetString("windows", resourceCulture);
            }
        }
    }
}
