//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tracker.Resources.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New KPI.
        /// </summary>
        public static string Add_Kpi {
            get {
                return ResourceManager.GetString("Add_Kpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New OKR.
        /// </summary>
        public static string Add_Okr {
            get {
                return ResourceManager.GetString("Add_Okr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New 1:1 .
        /// </summary>
        public static string Add_OneOnOne {
            get {
                return ResourceManager.GetString("Add_OneOnOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string Add_Project {
            get {
                return ResourceManager.GetString("Add_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string Add_Task {
            get {
                return ResourceManager.GetString("Add_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Team Member.
        /// </summary>
        public static string Add_Team_Member_Title {
            get {
                return ResourceManager.GetString("Add_Team_Member_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string ai {
            get {
                return ResourceManager.GetString("ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string android {
            get {
                return ResourceManager.GetString("android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architect.
        /// </summary>
        public static string architect {
            get {
                return ResourceManager.GetString("architect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string ColumnHeader_CellPhone {
            get {
                return ResourceManager.GetString("ColumnHeader_CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ColumnHeader_Date {
            get {
                return ResourceManager.GetString("ColumnHeader_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string ColumnHeader_Duration {
            get {
                return ResourceManager.GetString("ColumnHeader_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ColumnHeader_Email {
            get {
                return ResourceManager.GetString("ColumnHeader_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ColumnHeader_FirstName {
            get {
                return ResourceManager.GetString("ColumnHeader_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ColumnHeader_LastName {
            get {
                return ResourceManager.GetString("ColumnHeader_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string ColumnHeader_Role {
            get {
                return ResourceManager.GetString("ColumnHeader_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ColumnHeader_StartTime {
            get {
                return ResourceManager.GetString("ColumnHeader_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Member.
        /// </summary>
        public static string ColumnHeader_TeamMember {
            get {
                return ResourceManager.GetString("ColumnHeader_TeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ColumnHeaer_Status {
            get {
                return ResourceManager.GetString("ColumnHeaer_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Science.
        /// </summary>
        public static string data_science {
            get {
                return ResourceManager.GetString("data_science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Engineer.
        /// </summary>
        public static string engineer {
            get {
                return ResourceManager.GetString("engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full stack.
        /// </summary>
        public static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Instagram profile.
        /// </summary>
        public static string HintText_Instagram {
            get {
                return ResourceManager.GetString("HintText_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string HintText_Password {
            get {
                return ResourceManager.GetString("HintText_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        public static string HintText_UserName {
            get {
                return ResourceManager.GetString("HintText_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter X Profile.
        /// </summary>
        public static string HintText_XTwitter {
            get {
                return ResourceManager.GetString("HintText_XTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS.
        /// </summary>
        public static string ios {
            get {
                return ResourceManager.GetString("ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junior level.
        /// </summary>
        public static string junior {
            get {
                return ResourceManager.GetString("junior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Birthday.
        /// </summary>
        public static string Label_Birthday {
            get {
                return ResourceManager.GetString("Label_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday:.
        /// </summary>
        public static string Label_BirthdayColon {
            get {
                return ResourceManager.GetString("Label_BirthdayColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Label_Cell {
            get {
                return ResourceManager.GetString("Label_Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Facebook profile link.
        /// </summary>
        public static string Label_Facebook {
            get {
                return ResourceManager.GetString("Label_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hire Date.
        /// </summary>
        public static string Label_HireDate {
            get {
                return ResourceManager.GetString("Label_HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date:.
        /// </summary>
        public static string Label_HireDateColon {
            get {
                return ResourceManager.GetString("Label_HireDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Instagram profile link.
        /// </summary>
        public static string Label_Instagram {
            get {
                return ResourceManager.GetString("Label_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Label_JobTitle {
            get {
                return ResourceManager.GetString("Label_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title:.
        /// </summary>
        public static string Label_JobTitleColon {
            get {
                return ResourceManager.GetString("Label_JobTitleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter LinkedIn Profile Url.
        /// </summary>
        public static string Label_LinkIn {
            get {
                return ResourceManager.GetString("Label_LinkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string Label_NickName {
            get {
                return ResourceManager.GetString("Label_NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string Label_Role {
            get {
                return ResourceManager.GetString("Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of expertise:.
        /// </summary>
        public static string Label_Speciality {
            get {
                return ResourceManager.GetString("Label_Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Termination Date.
        /// </summary>
        public static string Label_TermDate {
            get {
                return ResourceManager.GetString("Label_TermDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination Date:.
        /// </summary>
        public static string Label_TerminationDateColon {
            get {
                return ResourceManager.GetString("Label_TerminationDateColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter X prolfile link.
        /// </summary>
        public static string Label_XTwitter {
            get {
                return ResourceManager.GetString("Label_XTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to Team Tracker.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacOS.
        /// </summary>
        public static string mac_os {
            get {
                return ResourceManager.GetString("mac_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Tracker.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string mgr {
            get {
                return ResourceManager.GetString("mgr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid level.
        /// </summary>
        public static string mid {
            get {
                return ResourceManager.GetString("mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Engineer.
        /// </summary>
        public static string principal {
            get {
                return ResourceManager.GetString("principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principle.
        /// </summary>
        public static string principle {
            get {
                return ResourceManager.GetString("principle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assurance .
        /// </summary>
        public static string qa {
            get {
                return ResourceManager.GetString("qa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string RadioButton_Active {
            get {
                return ResourceManager.GetString("RadioButton_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Theme.
        /// </summary>
        public static string RadioButton_Black {
            get {
                return ResourceManager.GetString("RadioButton_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Theme.
        /// </summary>
        public static string RadioButton_Gold {
            get {
                return ResourceManager.GetString("RadioButton_Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string RadioButton_Inactive {
            get {
                return ResourceManager.GetString("RadioButton_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Theme.
        /// </summary>
        public static string RadioButton_Light {
            get {
                return ResourceManager.GetString("RadioButton_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string sales {
            get {
                return ResourceManager.GetString("sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior level.
        /// </summary>
        public static string senior {
            get {
                return ResourceManager.GetString("senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string TabHeader_DatabaseSettings {
            get {
                return ResourceManager.GetString("TabHeader_DatabaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TabHeader_GeneralSettings {
            get {
                return ResourceManager.GetString("TabHeader_GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPIs.
        /// </summary>
        public static string TabHeader_KPIs {
            get {
                return ResourceManager.GetString("TabHeader_KPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKRs.
        /// </summary>
        public static string TabHeader_OKRs {
            get {
                return ResourceManager.GetString("TabHeader_OKRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1:1s.
        /// </summary>
        public static string TabHeader_OneOnOnes {
            get {
                return ResourceManager.GetString("TabHeader_OneOnOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string TabHeader_Projects {
            get {
                return ResourceManager.GetString("TabHeader_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TabHeader_Tasks {
            get {
                return ResourceManager.GetString("TabHeader_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        public static string TabHeader_TeamMembers {
            get {
                return ResourceManager.GetString("TabHeader_TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add KPI.
        /// </summary>
        public static string ToolTip_AddKpi {
            get {
                return ResourceManager.GetString("ToolTip_AddKpi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new team member.
        /// </summary>
        public static string ToolTip_AddMember {
            get {
                return ResourceManager.GetString("ToolTip_AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add OKR.
        /// </summary>
        public static string ToolTip_AddOKR {
            get {
                return ResourceManager.GetString("ToolTip_AddOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add One on One.
        /// </summary>
        public static string ToolTip_AddOneOnOne {
            get {
                return ResourceManager.GetString("ToolTip_AddOneOnOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        public static string ToolTip_AddProject {
            get {
                return ResourceManager.GetString("ToolTip_AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add task.
        /// </summary>
        public static string ToolTip_AddTask {
            get {
                return ResourceManager.GetString("ToolTip_AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Team member.
        /// </summary>
        public static string ToolTip_DeleteContact {
            get {
                return ResourceManager.GetString("ToolTip_DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ToolTip_Edit {
            get {
                return ResourceManager.GetString("ToolTip_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Facebook Profile.
        /// </summary>
        public static string ToolTip_Facebook {
            get {
                return ResourceManager.GetString("ToolTip_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Instagram Profile.
        /// </summary>
        public static string ToolTip_Instagram {
            get {
                return ResourceManager.GetString("ToolTip_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage KPIs.
        /// </summary>
        public static string ToolTip_KPIs {
            get {
                return ResourceManager.GetString("ToolTip_KPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to LinkedIn Profile.
        /// </summary>
        public static string ToolTip_LinkedIn {
            get {
                return ResourceManager.GetString("ToolTip_LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage OKRs.
        /// </summary>
        public static string ToolTip_OKRs {
            get {
                return ResourceManager.GetString("ToolTip_OKRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage 1:1 meetings.
        /// </summary>
        public static string ToolTip_OneOnOnes {
            get {
                return ResourceManager.GetString("ToolTip_OneOnOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Projects.
        /// </summary>
        public static string ToolTip_Projects {
            get {
                return ResourceManager.GetString("ToolTip_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ToolTip_Save {
            get {
                return ResourceManager.GetString("ToolTip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ToolTip_Settings {
            get {
                return ResourceManager.GetString("ToolTip_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Tasks.
        /// </summary>
        public static string ToolTip_Tasks {
            get {
                return ResourceManager.GetString("ToolTip_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Team Members.
        /// </summary>
        public static string ToolTip_TeamMembers {
            get {
                return ResourceManager.GetString("ToolTip_TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to X Profile.
        /// </summary>
        public static string ToolTip_TwitterX {
            get {
                return ResourceManager.GetString("ToolTip_TwitterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web UI.
        /// </summary>
        public static string web_ui {
            get {
                return ResourceManager.GetString("web_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string windows {
            get {
                return ResourceManager.GetString("windows", resourceCulture);
            }
        }
    }
}
