-- ============================================================================
-- ALTER TABLE: ai_insights - Add Missing Columns
-- Date: 2026-01-14
-- Purpose: Add columns that exist in the C# Insight model but were missing
--          from the original schema design
-- ============================================================================

-- Add severity column for insight severity level (info, warning, error, critical)
-- This is separate from priority which is about action urgency
ALTER TABLE ai_insights 
ADD COLUMN IF NOT EXISTS severity VARCHAR(20) NOT NULL DEFAULT 'info';

COMMENT ON COLUMN ai_insights.severity IS 'Severity level: info, warning, error, critical. Different from priority which is about action urgency.';

-- Add description column for detailed explanation (summary is the short version)
ALTER TABLE ai_insights 
ADD COLUMN IF NOT EXISTS description TEXT;

COMMENT ON COLUMN ai_insights.description IS 'Detailed description/explanation shown in the UI. Summary is the short version.';

-- Add action_suggestion column for the recommended action text
ALTER TABLE ai_insights 
ADD COLUMN IF NOT EXISTS action_suggestion TEXT;

COMMENT ON COLUMN ai_insights.action_suggestion IS 'Short suggestion for what action the user should take.';

-- Add entity_type column for polymorphic reference to related entity
ALTER TABLE ai_insights 
ADD COLUMN IF NOT EXISTS entity_type VARCHAR(50);

COMMENT ON COLUMN ai_insights.entity_type IS 'Type of entity this insight refers to: task, goal, metric, team_member, meeting, etc.';

-- Add entity_id column for the related entity UUID
ALTER TABLE ai_insights 
ADD COLUMN IF NOT EXISTS entity_id UUID;

COMMENT ON COLUMN ai_insights.entity_id IS 'UUID of the related entity when entity_type is set.';

-- Add generated_at column for when the insight was generated by the AI
ALTER TABLE ai_insights 
ADD COLUMN IF NOT EXISTS generated_at TIMESTAMPTZ NOT NULL DEFAULT now();

COMMENT ON COLUMN ai_insights.generated_at IS 'When this insight was generated by the AI system. May differ from created_at if there was a delay in persisting.';

-- ============================================================================
-- Verification Query
-- Run this after the ALTER statements to confirm columns were added
-- ============================================================================
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns 
-- WHERE table_schema = 'public' AND table_name = 'ai_insights'
-- ORDER BY ordinal_position;

-- ============================================================================
-- Updated Column Count: 28 original + 6 new = 34 columns
-- ============================================================================
