namespace ProCohere.Avalonia.Models;

/// <summary>
/// Type of insight generated by analyzers.
/// Maps to insight_type column in database.
/// </summary>
public enum InsightType
{
    /// <summary>Task is overdue.</summary>
    TaskOverdue,
    
    /// <summary>Task has been open for too long without progress.</summary>
    StaleActionItem,
    
    /// <summary>Goal is tracking behind schedule.</summary>
    GoalOffTrack,
    
    /// <summary>Goal is ahead of schedule (positive reinforcement).</summary>
    GoalOnTrack,
    
    /// <summary>One-on-one meeting is overdue.</summary>
    MeetingOverdue,
    
    /// <summary>One-on-one meeting is coming up soon.</summary>
    MeetingUpcoming,
    
    /// <summary>Goal is missing linked metrics.</summary>
    MetricMissing,
    
    /// <summary>Metric value is declining.</summary>
    MetricDeclining,
    
    /// <summary>Personal date reminder (birthday, work anniversary).</summary>
    PersonalDate,
    
    /// <summary>Pulse survey sentiment is declining.</summary>
    SentimentDeclining,
    
    /// <summary>Pulse survey sentiment is improving (positive reinforcement).</summary>
    SentimentImproving
}

/// <summary>
/// Severity level of an insight.
/// Maps to severity column in database.
/// </summary>
public enum InsightSeverity
{
    /// <summary>Informational, low priority.</summary>
    Low,
    
    /// <summary>Worth noting, moderate priority.</summary>
    Medium,
    
    /// <summary>Important, needs attention soon.</summary>
    High,
    
    /// <summary>Urgent, requires immediate action.</summary>
    Critical
}

/// <summary>
/// Current status of an insight.
/// Maps to status column in database.
/// </summary>
public enum InsightStatus
{
    /// <summary>Active and visible to user.</summary>
    Active,
    
    /// <summary>User dismissed the insight.</summary>
    Dismissed,
    
    /// <summary>User took action on the insight.</summary>
    ActedOn,
    
    /// <summary>User snoozed the insight until a future date.</summary>
    Snoozed
}
