using System;

namespace Tracker.DataModels
{
    /// <summary>
    /// Represents a proactive insight generated by the AI system.
    /// Insights notify managers of items requiring attention.
    /// </summary>
    public class Insight
    {
        /// <summary>
        /// Unique identifier for the insight.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Unique key for deduplication (e.g., "meeting_gap_sarah_2025-12").
        /// </summary>
        public string UniqueKey { get; set; } = string.Empty;

        /// <summary>
        /// The type/category of insight.
        /// </summary>
        public InsightType Type { get; set; }

        /// <summary>
        /// Severity level determining visual treatment and priority.
        /// </summary>
        public InsightSeverity Severity { get; set; }

        /// <summary>
        /// Short, actionable title (displayed prominently).
        /// </summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Detailed description with context.
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Suggested action the manager can take.
        /// </summary>
        public string ActionSuggestion { get; set; } = string.Empty;

        /// <summary>
        /// When the insight was generated.
        /// </summary>
        public DateTime GeneratedAt { get; set; } = DateTime.Now;

        /// <summary>
        /// When the user dismissed this insight (null if not dismissed).
        /// </summary>
        public DateTime? DismissedAt { get; set; }

        /// <summary>
        /// When the user took action on this insight (null if no action taken).
        /// </summary>
        public DateTime? ActedOnAt { get; set; }

        /// <summary>
        /// Whether the user has viewed this insight.
        /// </summary>
        public bool IsRead { get; set; }

        /// <summary>
        /// The type of entity this insight relates to (e.g., "TeamMember", "Meeting", "OKR").
        /// </summary>
        public string? EntityType { get; set; }

        /// <summary>
        /// The ID of the related entity for deep-linking.
        /// </summary>
        public int? EntityId { get; set; }

        /// <summary>
        /// Checks if the insight is still active (not dismissed).
        /// </summary>
        public bool IsActive => DismissedAt == null;

        /// <summary>
        /// Gets the icon for this insight type.
        /// </summary>
        public string Icon => Type switch
        {
            InsightType.MeetingGap => "👥",
            InsightType.OkrAtRisk => "🎯",
            InsightType.KpiOffTarget => "📊",
            InsightType.UpcomingBirthday => "🎂",
            InsightType.UpcomingAnniversary => "🎉",
            InsightType.StaleActionItem => "📋",
            InsightType.SurveyAlert => "📝",
            InsightType.TaskOverdue => "⚠️",
            InsightType.MeetingToday => "📅",
            InsightType.OkrEndingSoon => "⏰",
            InsightType.KudosSuggestion => "⭐",
            _ => "💡"
        };
    }

    /// <summary>
    /// Categories of insights the system can generate.
    /// </summary>
    public enum InsightType
    {
        /// <summary>
        /// Team member hasn't had a 1:1 in X days.
        /// </summary>
        MeetingGap,

        /// <summary>
        /// OKR trajectory predicts a miss.
        /// </summary>
        OkrAtRisk,

        /// <summary>
        /// KPI significantly below target.
        /// </summary>
        KpiOffTarget,

        /// <summary>
        /// Team member birthday in next 7 days.
        /// </summary>
        UpcomingBirthday,

        /// <summary>
        /// Work anniversary in next 7 days.
        /// </summary>
        UpcomingAnniversary,

        /// <summary>
        /// Action item from meeting is stale (>14 days old).
        /// </summary>
        StaleActionItem,

        /// <summary>
        /// Low rating received in pulse survey.
        /// </summary>
        SurveyAlert,

        /// <summary>
        /// Task is past its due date.
        /// </summary>
        TaskOverdue,

        /// <summary>
        /// 1:1 meeting scheduled for today.
        /// </summary>
        MeetingToday,

        /// <summary>
        /// OKR period ending within 7 days.
        /// </summary>
        OkrEndingSoon,

        /// <summary>
        /// Suggestion to send kudos to a team member.
        /// </summary>
        KudosSuggestion
    }

    /// <summary>
    /// Severity levels for insights, determining visual treatment.
    /// </summary>
    public enum InsightSeverity
    {
        /// <summary>
        /// Informational - Blue - FYI, no action required.
        /// </summary>
        Info,

        /// <summary>
        /// Warning - Amber - Needs attention soon.
        /// </summary>
        Warning,

        /// <summary>
        /// Critical - Red - Needs immediate attention.
        /// </summary>
        Critical
    }
}
