using System;
using System.Collections.Generic;
using Tracker.Common.Enums;

namespace Tracker.DataModels
{
    /// <summary>
    /// Represents a proactive insight generated by the AI system.
    /// Insights can target the organization, a specific team, or a team member.
    /// </summary>
    public class Insight
    {
        /// <summary>
        /// Unique identifier for the insight.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// The organization that owns this insight.
        /// </summary>
        public Guid OrganizationId { get; set; }
        public Organization? Organization { get; set; }

        /// <summary>
        /// The target team for this insight (optional; null if org-wide or team-member-specific).
        /// </summary>
        public Guid? TargetTeamId { get; set; }
        public Team? TargetTeam { get; set; }

        /// <summary>
        /// The target team member for this insight (optional; null if org-wide or team-wide).
        /// </summary>
        public Guid? TargetTeamMemberId { get; set; }
        public TeamMember? TargetTeamMember { get; set; }

        /// <summary>
        /// The type of insight (e.g., risk_alert, opportunity, trend, recommendation).
        /// </summary>
        public string InsightType { get; set; } = string.Empty;

        /// <summary>
        /// The category of insight (e.g., engagement, performance, retention, goal_progress).
        /// </summary>
        public string Category { get; set; } = string.Empty;

        /// <summary>
        /// Short, actionable title (displayed prominently).
        /// </summary>
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Summary of the insight.
        /// </summary>
        public string Summary { get; set; } = string.Empty;

        /// <summary>
        /// Stable unique key used for deduplication in the local store.
        /// </summary>
        public string UniqueKey { get; set; } = string.Empty;

        /// <summary>
        /// High-level insight type used by the rules and AI engine.
        /// </summary>
        public InsightType Type { get; set; }

        /// <summary>
        /// Severity level used for prioritizing insights.
        /// </summary>
        public InsightSeverity Severity { get; set; } = InsightSeverity.Info;

        /// <summary>
        /// Detailed description text shown in the UI.
        /// </summary>
        public string Description { get; set; } = string.Empty;

        /// <summary>
        /// Short suggestion for what action the user should take.
        /// </summary>
        public string? ActionSuggestion { get; set; }

        /// <summary>
        /// Logical entity type this insight refers to (e.g., "TrackerTask").
        /// </summary>
        public string? EntityType { get; set; }

        /// <summary>
        /// Numeric identifier for the referenced entity when applicable.
        /// </summary>
        public int? EntityId { get; set; }

        /// <summary>
        /// Structured data supporting the insight (JSONB in Supabase).
        /// </summary>
        public Dictionary<string, object>? Details { get; set; }

        /// <summary>
        /// Priority level: low, medium, high, critical.
        /// </summary>
        public string Priority { get; set; } = "medium";

        /// <summary>
        /// Recommended actions as structured data (JSONB in Supabase).
        /// </summary>
        public List<Dictionary<string, object>>? RecommendedActions { get; set; }

        /// <summary>
        /// Source entities that led to this insight (e.g., [{type: 'metric', id: '...'}]).
        /// </summary>
        public List<Dictionary<string, object>>? SourceEntities { get; set; }

        /// <summary>
        /// When this insight instance was generated.
        /// </summary>
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When this insight becomes valid.
        /// </summary>
        public DateTime ValidFrom { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When this insight expires (optional; null if no expiry).
        /// </summary>
        public DateTime? ValidUntil { get; set; }

        /// <summary>
        /// Whether the user has dismissed this insight.
        /// </summary>
        public bool IsDismissed { get; set; }

        /// <summary>
        /// When the user dismissed this insight (null if not dismissed).
        /// </summary>
        public DateTime? DismissedAt { get; set; }

        /// <summary>
        /// The user who dismissed this insight (optional).
        /// </summary>
        public Guid? DismissedBy { get; set; }
        public User? DismissedByUser { get; set; }

        /// <summary>
        /// Reason why the insight was dismissed.
        /// </summary>
        public string? DismissReason { get; set; }

        /// <summary>
        /// Whether the user has taken action on this insight.
        /// </summary>
        public bool IsActioned { get; set; }

        /// <summary>
        /// Whether the insight has been marked as read in the client.
        /// </summary>
        public bool IsRead { get; set; }

        /// <summary>
        /// When the user took action on this insight (null if no action taken).
        /// </summary>
        public DateTime? ActionedAt { get; set; }

        /// <summary>
        /// Notes about the action taken on this insight.
        /// </summary>
        public string? ActionNotes { get; set; }

        /// <summary>
        /// When the insight was created.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Checks if the insight is still active (not dismissed and valid).
        /// </summary>
        public bool IsActive => !IsDismissed && ValidFrom <= DateTime.UtcNow && (ValidUntil == null || ValidUntil > DateTime.UtcNow);
    }
}
