using System.Text.Json;

namespace Tracker.DataModels
{
    /// <summary>
    /// Stores vector embeddings for semantic search across the application.
    /// 
    /// Embeddings are generated by AI models (e.g., OpenAI ada-002) to enable
    /// similarity search across team members, meetings, tasks, and other entities.
    /// 
    /// Storage:
    /// - PostgreSQL: Uses pgvector extension for native vector operations
    /// - SQL Server: Stores as VARBINARY, similarity calculated in application
    /// 
    /// All embeddings are scoped to an organization via OrganizationId.
    /// </summary>
    public class VectorEmbedding : AuditableEntity
    {
        /// <summary>
        /// Primary key - GUID for PostgreSQL compatibility.
        /// </summary>
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// The organization this embedding belongs to.
        /// Null for system-level embeddings (e.g., help documentation).
        /// </summary>
        public Guid? OrganizationId { get; set; }

        /// <summary>
        /// Type of entity this embedding represents.
        /// Examples: "team_member", "meeting", "task", "okr", "document", "help"
        /// </summary>
        public string EntityType { get; set; } = string.Empty;

        /// <summary>
        /// ID of the source entity (as string to support different ID types).
        /// For database entities, this is typically the primary key.
        /// For documents, this could be a file path or document ID.
        /// </summary>
        public string EntityId { get; set; } = string.Empty;

        /// <summary>
        /// Chunk index for long content that was split.
        /// Most entities have a single chunk (index 0).
        /// Documents may have multiple chunks.
        /// </summary>
        public int ChunkIndex { get; set; } = 0;

        /// <summary>
        /// The original text content that was embedded.
        /// Stored for search result display and debugging.
        /// </summary>
        public string Content { get; set; } = string.Empty;

        /// <summary>
        /// The vector embedding as a byte array.
        /// Serialized from float[] using binary serialization.
        /// 
        /// For PostgreSQL with pgvector, this may be stored differently
        /// via a custom value converter.
        /// </summary>
        public byte[] Embedding { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// Number of dimensions in the embedding vector.
        /// OpenAI ada-002: 1536 dimensions
        /// OpenAI text-embedding-3-small: 1536 dimensions
        /// OpenAI text-embedding-3-large: 3072 dimensions
        /// </summary>
        public int EmbeddingDimensions { get; set; } = 1536;

        /// <summary>
        /// JSON metadata for additional context.
        /// Can include: entity name, dates, tags, relevance hints, etc.
        /// </summary>
        public string? MetadataJson { get; set; }

        #region Navigation Properties

        /// <summary>
        /// The organization this embedding belongs to (if scoped).
        /// </summary>
        public Organization? Organization { get; set; }

        #endregion

        #region Embedding Serialization

        /// <summary>
        /// Gets or sets the embedding as a float array.
        /// Automatically serializes to/from the byte array storage.
        /// </summary>
        public float[] EmbeddingVector
        {
            get => DeserializeEmbedding(Embedding);
            set => Embedding = SerializeEmbedding(value);
        }

        /// <summary>
        /// Serializes a float array to bytes for storage.
        /// </summary>
        public static byte[] SerializeEmbedding(float[] vector)
        {
            if (vector == null || vector.Length == 0)
                return Array.Empty<byte>();

            var bytes = new byte[vector.Length * sizeof(float)];
            Buffer.BlockCopy(vector, 0, bytes, 0, bytes.Length);
            return bytes;
        }

        /// <summary>
        /// Deserializes bytes back to a float array.
        /// </summary>
        public static float[] DeserializeEmbedding(byte[] bytes)
        {
            if (bytes == null || bytes.Length == 0)
                return Array.Empty<float>();

            var vector = new float[bytes.Length / sizeof(float)];
            Buffer.BlockCopy(bytes, 0, vector, 0, bytes.Length);
            return vector;
        }

        #endregion

        #region Metadata Helpers

        /// <summary>
        /// Gets the metadata as a dictionary.
        /// </summary>
        public Dictionary<string, object>? GetMetadata()
        {
            if (string.IsNullOrEmpty(MetadataJson))
                return null;

            try
            {
                return JsonSerializer.Deserialize<Dictionary<string, object>>(MetadataJson);
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Sets the metadata from a dictionary.
        /// </summary>
        public void SetMetadata(Dictionary<string, object>? metadata)
        {
            if (metadata == null || metadata.Count == 0)
            {
                MetadataJson = null;
                return;
            }

            MetadataJson = JsonSerializer.Serialize(metadata);
        }

        /// <summary>
        /// Gets a specific metadata value.
        /// </summary>
        public T? GetMetadataValue<T>(string key)
        {
            var metadata = GetMetadata();
            if (metadata == null || !metadata.TryGetValue(key, out var value))
                return default;

            try
            {
                if (value is JsonElement element)
                {
                    return JsonSerializer.Deserialize<T>(element.GetRawText());
                }
                return (T)Convert.ChangeType(value, typeof(T));
            }
            catch
            {
                return default;
            }
        }

        #endregion

        #region Similarity Calculation

        /// <summary>
        /// Calculates cosine similarity between this embedding and another vector.
        /// Returns a value between -1 and 1, where 1 is most similar.
        /// </summary>
        public float CalculateSimilarity(float[] other)
        {
            return CosineSimilarity(EmbeddingVector, other);
        }

        /// <summary>
        /// Calculates cosine similarity between two vectors.
        /// </summary>
        public static float CosineSimilarity(float[] a, float[] b)
        {
            if (a.Length != b.Length || a.Length == 0)
                return 0f;

            float dot = 0f, magA = 0f, magB = 0f;
            
            for (int i = 0; i < a.Length; i++)
            {
                dot += a[i] * b[i];
                magA += a[i] * a[i];
                magB += b[i] * b[i];
            }

            if (magA == 0f || magB == 0f)
                return 0f;

            return dot / (MathF.Sqrt(magA) * MathF.Sqrt(magB));
        }

        #endregion
    }
}
