using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json;

namespace Tracker.DataModels
{
    /// <summary>
    /// Stores vector embeddings for semantic search across the application.
    /// Maps to Supabase 'vector_embeddings' table (18 columns after ALTER).
    /// 
    /// Embeddings are generated by AI models (e.g., OpenAI ada-002) to enable
    /// similarity search across team members, meetings, tasks, and other entities.
    /// 
    /// Storage: PostgreSQL with pgvector extension for native vector operations.
    /// All embeddings are scoped to an organization via OrganizationId.
    /// </summary>
    [Table("vector_embeddings")]
    public class VectorEmbedding : AuditableEntity
    {
        #region Primary Key & Foreign Keys

        /// <summary>
        /// Primary key.
        /// Maps to: id UUID NOT NULL DEFAULT gen_random_uuid()
        /// </summary>
        [Column("id")]
        public Guid Id { get; set; } = Guid.NewGuid();

        /// <summary>
        /// The organization this embedding belongs to.
        /// Maps to: organization_id UUID NOT NULL
        /// </summary>
        [Column("organization_id")]
        public Guid OrganizationId { get; set; }

        #endregion

        #region Entity Reference

        /// <summary>
        /// Type of entity this embedding represents.
        /// Examples: "team_member", "meeting", "task", "goal", "document", "help"
        /// Maps to: entity_type VARCHAR(50) NOT NULL
        /// </summary>
        [Column("entity_type")]
        [Required]
        [MaxLength(50)]
        public string EntityType { get; set; } = string.Empty;

        /// <summary>
        /// ID of the source entity (UUID).
        /// Maps to: entity_id UUID NOT NULL
        /// </summary>
        [Column("entity_id")]
        public Guid EntityId { get; set; }

        /// <summary>
        /// Chunk index for long content that was split.
        /// Most entities have a single chunk (index 0).
        /// Maps to: chunk_index INTEGER NOT NULL DEFAULT 0 (ADDED)
        /// </summary>
        [Column("chunk_index")]
        public int ChunkIndex { get; set; } = 0;

        #endregion

        #region Content

        /// <summary>
        /// Hash of content for deduplication.
        /// Maps to: content_hash VARCHAR(64) NOT NULL
        /// </summary>
        [Column("content_hash")]
        [Required]
        [MaxLength(64)]
        public string ContentHash { get; set; } = string.Empty;

        /// <summary>
        /// Preview of content (first 500 chars).
        /// Maps to: content_preview VARCHAR(500) NULL
        /// </summary>
        [Column("content_preview")]
        [MaxLength(500)]
        public string? ContentPreview { get; set; }

        /// <summary>
        /// The full original text content that was embedded.
        /// Maps to: content TEXT NULL (ADDED)
        /// </summary>
        [Column("content")]
        public string? Content { get; set; }

        #endregion

        #region Embedding

        /// <summary>
        /// The vector embedding stored in pgvector native format.
        /// Maps to: embedding VECTOR NULL
        /// Note: Dapper/Npgsql requires custom type handler for pgvector.
        /// </summary>
        [Column("embedding")]
        public float[]? EmbeddingVector { get; set; }

        /// <summary>
        /// Number of dimensions in the embedding vector.
        /// OpenAI ada-002: 1536, text-embedding-3-large: 3072
        /// Maps to: embedding_dimensions INTEGER NOT NULL DEFAULT 1536 (ADDED)
        /// </summary>
        [Column("embedding_dimensions")]
        public int EmbeddingDimensions { get; set; } = 1536;

        #endregion

        #region Model Info

        /// <summary>
        /// Name of the embedding model used.
        /// Maps to: model_name VARCHAR(100) NOT NULL DEFAULT 'text-embedding-ada-002'
        /// </summary>
        [Column("model_name")]
        [Required]
        [MaxLength(100)]
        public string ModelName { get; set; } = "text-embedding-ada-002";

        /// <summary>
        /// Version of the embedding model.
        /// Maps to: model_version VARCHAR(50) NULL
        /// </summary>
        [Column("model_version")]
        [MaxLength(50)]
        public string? ModelVersion { get; set; }

        #endregion

        #region Metadata

        /// <summary>
        /// JSON metadata for additional context.
        /// Maps to: metadata JSONB NULL
        /// </summary>
        [Column("metadata")]
        public string? MetadataJson { get; set; }

        #endregion

        #region Navigation Properties

        /// <summary>
        /// The organization this embedding belongs to.
        /// </summary>
        public Organization? Organization { get; set; }

        #endregion

        #region Metadata Helpers

        /// <summary>
        /// Gets the metadata as a dictionary.
        /// </summary>
        public Dictionary<string, object>? GetMetadata()
        {
            if (string.IsNullOrEmpty(MetadataJson))
                return null;

            try
            {
                return JsonSerializer.Deserialize<Dictionary<string, object>>(MetadataJson);
            }
            catch
            {
                return null;
            }
        }

        /// <summary>
        /// Sets the metadata from a dictionary.
        /// </summary>
        public void SetMetadata(Dictionary<string, object>? metadata)
        {
            if (metadata == null || metadata.Count == 0)
            {
                MetadataJson = null;
                return;
            }

            MetadataJson = JsonSerializer.Serialize(metadata);
        }

        /// <summary>
        /// Gets a specific metadata value.
        /// </summary>
        public T? GetMetadataValue<T>(string key)
        {
            var metadata = GetMetadata();
            if (metadata == null || !metadata.TryGetValue(key, out var value))
                return default;

            try
            {
                if (value is JsonElement element)
                {
                    return JsonSerializer.Deserialize<T>(element.GetRawText());
                }
                return (T)Convert.ChangeType(value, typeof(T));
            }
            catch
            {
                return default;
            }
        }

        #endregion

        #region Similarity Calculation

        /// <summary>
        /// Calculates cosine similarity between this embedding and another vector.
        /// Returns a value between -1 and 1, where 1 is most similar.
        /// </summary>
        public float CalculateSimilarity(float[] other)
        {
            return CosineSimilarity(EmbeddingVector ?? Array.Empty<float>(), other);
        }

        /// <summary>
        /// Calculates cosine similarity between two vectors.
        /// </summary>
        public static float CosineSimilarity(float[] a, float[] b)
        {
            if (a.Length != b.Length || a.Length == 0)
                return 0f;

            float dot = 0f, magA = 0f, magB = 0f;
            
            for (int i = 0; i < a.Length; i++)
            {
                dot += a[i] * b[i];
                magA += a[i] * a[i];
                magB += b[i] * b[i];
            }

            if (magA == 0f || magB == 0f)
                return 0f;

            return dot / (MathF.Sqrt(magA) * MathF.Sqrt(magB));
        }

        #endregion
    }
}
