using System.ComponentModel.DataAnnotations.Schema;
using Tracker.Core.Common.Enums;

namespace Tracker.Core.DataModels
{
    /// <summary>
    /// Represents a proactive insight generated by the AI system.
    /// Maps to Supabase 'ai_insights' table (34 columns after ALTER).
    /// Insights can target the organization, a specific team, or a team member.
    /// </summary>
    [Table("ai_insights")]
    public class Insight : AuditableEntity
    {
        #region Primary Key & Foreign Keys

        /// <summary>
        /// Unique identifier for the insight.
        /// Maps to: id UUID NOT NULL DEFAULT gen_random_uuid()
        /// </summary>
        [Column("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// The organization that owns this insight.
        /// Maps to: organization_id UUID NOT NULL
        /// </summary>
        [Column("organization_id")]
        public Guid OrganizationId { get; set; }

        /// <summary>
        /// The target team for this insight (optional; null if org-wide or team-member-specific).
        /// Maps to: target_team_id UUID NULL
        /// </summary>
        [Column("target_team_id")]
        public Guid? TargetTeamId { get; set; }

        /// <summary>
        /// The target team member for this insight (optional; null if org-wide or team-wide).
        /// Maps to: target_team_member_id UUID NULL
        /// </summary>
        [Column("target_team_member_id")]
        public Guid? TargetTeamMemberId { get; set; }

        #endregion

        #region Insight Classification

        /// <summary>
        /// The type of insight (e.g., risk_alert, opportunity, trend, recommendation).
        /// Maps to: insight_type VARCHAR(100) NOT NULL
        /// </summary>
        [Column("insight_type")]
        public string InsightType { get; set; } = string.Empty;

        /// <summary>
        /// High-level insight type enum used by the rules and AI engine.
        /// Stored as string in insight_type column.
        /// </summary>
        [NotMapped]
        public InsightType Type
        {
            get => Enum.TryParse<InsightType>(InsightType, true, out var result) ? result : Common.Enums.InsightType.General;
            set => InsightType = value.ToString().ToLowerInvariant();
        }

        /// <summary>
        /// The category of insight (e.g., engagement, performance, retention, goal_progress).
        /// Maps to: category VARCHAR(100) NOT NULL
        /// </summary>
        [Column("category")]
        public string Category { get; set; } = string.Empty;

        /// <summary>
        /// Priority level: low, medium, high, critical.
        /// Maps to: priority VARCHAR(20) NOT NULL DEFAULT 'medium'
        /// </summary>
        [Column("priority")]
        public string Priority { get; set; } = "medium";

        /// <summary>
        /// Severity level: info, warning, error, critical.
        /// Different from priority which is about action urgency.
        /// Maps to: severity VARCHAR(20) NOT NULL DEFAULT 'info'
        /// </summary>
        [Column("severity")]
        public string SeverityString { get; set; } = "info";

        /// <summary>
        /// Severity enum accessor for code convenience.
        /// </summary>
        [NotMapped]
        public InsightSeverity Severity
        {
            get => Enum.TryParse<InsightSeverity>(SeverityString, true, out var result) ? result : InsightSeverity.Info;
            set => SeverityString = value.ToString().ToLowerInvariant();
        }

        #endregion

        #region Content

        /// <summary>
        /// Short, actionable title (displayed prominently).
        /// Maps to: title VARCHAR(200) NOT NULL
        /// </summary>
        [Column("title")]
        public string Title { get; set; } = string.Empty;

        /// <summary>
        /// Brief summary of the insight.
        /// Maps to: summary TEXT NOT NULL
        /// </summary>
        [Column("summary")]
        public string Summary { get; set; } = string.Empty;

        /// <summary>
        /// Detailed description/explanation shown in the UI.
        /// Maps to: description TEXT NULL
        /// </summary>
        [Column("description")]
        public string? Description { get; set; }

        /// <summary>
        /// Short suggestion for what action the user should take.
        /// Maps to: action_suggestion TEXT NULL
        /// </summary>
        [Column("action_suggestion")]
        public string? ActionSuggestion { get; set; }

        /// <summary>
        /// Structured data supporting the insight.
        /// Maps to: details JSONB NULL
        /// </summary>
        [Column("details")]
        public string? DetailsJson { get; set; }

        /// <summary>
        /// Recommended actions as structured data.
        /// Maps to: recommended_actions JSONB NULL
        /// </summary>
        [Column("recommended_actions")]
        public string? RecommendedActionsJson { get; set; }

        /// <summary>
        /// Source entities that led to this insight (e.g., [{type: 'metric', id: '...'}]).
        /// Maps to: source_entities JSONB NULL
        /// </summary>
        [Column("source_entities")]
        public string? SourceEntitiesJson { get; set; }

        /// <summary>
        /// Stable unique key used for deduplication.
        /// Maps to: unique_key VARCHAR(255) NULL
        /// </summary>
        [Column("unique_key")]
        public string? UniqueKey { get; set; }

        #endregion

        #region Entity Reference (Polymorphic Link)

        /// <summary>
        /// Type of entity this insight refers to: task, goal, metric, team_member, meeting, etc.
        /// Maps to: entity_type VARCHAR(50) NULL
        /// </summary>
        [Column("entity_type")]
        public string? EntityType { get; set; }

        /// <summary>
        /// UUID of the related entity when entity_type is set.
        /// Maps to: entity_id UUID NULL
        /// </summary>
        [Column("entity_id")]
        public Guid? EntityId { get; set; }

        #endregion

        #region Timestamps

        /// <summary>
        /// When this insight was generated by the AI system.
        /// May differ from created_at if there was a delay in persisting.
        /// Maps to: generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        /// </summary>
        [Column("generated_at")]
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When this insight becomes valid.
        /// Maps to: valid_from TIMESTAMPTZ NOT NULL
        /// </summary>
        [Column("valid_from")]
        public DateTime ValidFrom { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// When this insight expires (optional; null if no expiry).
        /// Maps to: valid_until TIMESTAMPTZ NULL
        /// </summary>
        [Column("valid_until")]
        public DateTime? ValidUntil { get; set; }

        #endregion

        #region User Interaction - Dismissal

        /// <summary>
        /// Whether the user has dismissed this insight.
        /// Maps to: is_dismissed BOOLEAN NOT NULL DEFAULT false
        /// </summary>
        [Column("is_dismissed")]
        public bool IsDismissed { get; set; }

        /// <summary>
        /// When the user dismissed this insight (null if not dismissed).
        /// Maps to: dismissed_at TIMESTAMPTZ NULL
        /// </summary>
        [Column("dismissed_at")]
        public DateTime? DismissedAt { get; set; }

        /// <summary>
        /// The user who dismissed this insight (UUID FK to users).
        /// Maps to: dismissed_by UUID NULL
        /// </summary>
        [Column("dismissed_by")]
        public Guid? DismissedBy { get; set; }

        /// <summary>
        /// Reason why the insight was dismissed.
        /// Maps to: dismiss_reason TEXT NULL
        /// </summary>
        [Column("dismiss_reason")]
        public string? DismissReason { get; set; }

        #endregion

        #region User Interaction - Action

        /// <summary>
        /// Whether the user has taken action on this insight.
        /// Maps to: is_actioned BOOLEAN NOT NULL DEFAULT false
        /// </summary>
        [Column("is_actioned")]
        public bool IsActioned { get; set; }

        /// <summary>
        /// When the user took action on this insight (null if no action taken).
        /// Maps to: actioned_at TIMESTAMPTZ NULL
        /// </summary>
        [Column("actioned_at")]
        public DateTime? ActionedAt { get; set; }

        /// <summary>
        /// Notes about the action taken on this insight.
        /// Maps to: action_notes TEXT NULL
        /// </summary>
        [Column("action_notes")]
        public string? ActionNotes { get; set; }

        /// <summary>
        /// Whether the insight has been marked as read in the client.
        /// Maps to: is_read BOOLEAN NOT NULL DEFAULT false
        /// </summary>
        [Column("is_read")]
        public bool IsRead { get; set; }

        #endregion

        #region Navigation Properties (Not Mapped to Database)

        /// <summary>
        /// Navigation property to the organization.
        /// </summary>
        [NotMapped]
        public Organization? Organization { get; set; }

        /// <summary>
        /// Navigation property to the target team.
        /// </summary>
        [NotMapped]
        public Team? TargetTeam { get; set; }

        /// <summary>
        /// Navigation property to the target team member.
        /// </summary>
        [NotMapped]
        public TeamMember? TargetTeamMember { get; set; }

        /// <summary>
        /// Navigation property to the user who dismissed this insight.
        /// </summary>
        [NotMapped]
        public User? DismissedByUser { get; set; }

        #endregion

        #region Computed Properties

        /// <summary>
        /// Checks if the insight is still active (not dismissed and valid).
        /// </summary>
        [NotMapped]
        public bool IsActive => !IsDismissed && !IsDeleted && 
            ValidFrom <= DateTime.UtcNow && 
            (ValidUntil == null || ValidUntil > DateTime.UtcNow);

        /// <summary>
        /// Details - alias for DetailsJson for backward compatibility.
        /// </summary>
        [NotMapped]
        public string? Details
        {
            get => DetailsJson;
            set => DetailsJson = value;
        }

        /// <summary>
        /// RecommendedActions - alias for RecommendedActionsJson for backward compatibility.
        /// </summary>
        [NotMapped]
        public string? RecommendedActions
        {
            get => RecommendedActionsJson;
            set => RecommendedActionsJson = value;
        }

        /// <summary>
        /// SourceEntities - alias for SourceEntitiesJson for backward compatibility.
        /// </summary>
        [NotMapped]
        public string? SourceEntities
        {
            get => SourceEntitiesJson;
            set => SourceEntitiesJson = value;
        }

        #endregion
    }
}
